# Generated by Django 6.0.5 on 2026-05-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_securitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
    ]
